src/Vecindapp/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.home import views as home_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include(('apps.users.urls', 'user'), namespace='user')),
    path('', include(('apps.home.urls', 'home'), namespace='home')),
]

src/apps/home/urls.py
# Django Imports
from django.urls import path

# Local Imports
from apps.home import views

urlpatterns = [
    path(
        route = '',
        view = views.index,
        name = 'welcome',
    )

]

src/apps/users/urls.py
# Django Imports
from django.urls import path

# Local Imports
from apps.users import views

urlpatterns = [
    path(
        route = 'signup/',
        view = views.SignUpView.as_view(),
        name = 'signup'
    ),
    path(
        route = 'login/',
        view = views.LoginView.as_view(),
        name = 'login'
    ),
    path(
        route='logout/',
        view=views.LogoutView.as_view(),
        name='logout'
    ),
    path(
        route = 'update/residente',
        view = views.ResidentProfileUpdateView.as_view(),
        name = 'update_rprofile'
    ),
    path(
        route = 'update/vigilante',
        view = views.WatchmanProfileUpdateView.as_view(),
        name = 'update_wprofile'
    ),
]

src/apps/home/models.py
from django.db import models

# Create your models here.

src/apps/users/models.py
# Import Django User model
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.
class User(AbstractUser):
    phone_number = models.CharField(max_length=25, blank=True)
    RESIDENT = 1
    WATCHMAN = 2
    NOT_DEFINED = 3
    ROLE_CHOICES = (
        (NOT_DEFINED, 'No Definido'),
        (WATCHMAN, 'Vigilante'),
        (RESIDENT, 'Residente'),
    )
    role = models.PositiveSmallIntegerField(choices=ROLE_CHOICES, default=NOT_DEFINED)


class WatchmanProfile(models.Model):
    """ Define el modelo de Watchman, el cual será una extensión del modelo User
        que hereda de CommonInfo.
    """
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name='w_profile',
        null=True
    )
    id_num = models.PositiveSmallIntegerField(blank=False, unique=True, null=True)

    # Meta Data
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.first_name + self.user.last_name


class ResidentProfile(models.Model):
    """ Define el modelo de Resident, el cual será una extensión del modelo User
        que hereda de CommonInfo.
    """
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name='r_profile',
        null=True,
    )
    OWNER = 1
    TENANT = 2
    NOT_DEFINED = 3
    RELATION_W_PROPERTY = (
        (OWNER, 'PROPIETARIO'),
        (TENANT, 'ARRENDATARIO'),
        (NOT_DEFINED, 'NO DEFINIDO')
    )
    building_num = models.PositiveSmallIntegerField(blank=True, null=True)
    apartment_num = models.PositiveSmallIntegerField(blank=True, null=True)
    parking_lot_num = models.PositiveSmallIntegerField(blank=True, null=True)
    property_relation = models.PositiveSmallIntegerField(
        choices=RELATION_W_PROPERTY,
        default=NOT_DEFINED,
        blank=False,
    )

    # Meta Data
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.first_name + self.user.last_name

src/apps/users/forms.py
# Django Imports
from django import forms

# Local Imports
from .models import User, ResidentProfile, WatchmanProfile


class SignUpForm(forms.Form):
    username = forms.CharField(
        min_length=4,
        max_length=50,
        label='Nombre de Usuario'
    )
    email = forms.CharField(
        min_length=6,
        max_length=70,
        widget=forms.EmailInput(),
        label='Correo Electrónico'
    )
    password = forms.CharField(
        max_length=50,
        widget=forms.PasswordInput(),
        label='Contraseña'
    )
    password_confirmation = forms.CharField(
        max_length=50,
        widget=forms.PasswordInput(),
        label='Confirme su Contraseña'
    )
    first_name = forms.CharField(
        min_length=2,
        max_length=50,
        label='Nombre(s)'
    )
    last_name = forms.CharField(
        min_length=2,
        max_length=50,
        label='Apellido(s)'
    )
    RESIDENT = 1
    WATCHMAN = 2
    ROLE_CHOICES = (
        (RESIDENT, 'Residente'),
        (WATCHMAN, 'Vigilante'),
    )
    role = forms.ChoiceField(
        choices=ROLE_CHOICES,
        label='¿Cúal es tú rol?'
    )
    phone_number = forms.CharField(
        min_length=7,
        max_length=50,
        required=False,
        label='Teléfono'
    )

    def clean_email(self):
        email = self.cleaned_data['email']
        username = self.cleaned_data['username']
        if email and User.objects.filter(email=email).exclude(username=username).exists():
            raise forms.ValidationError(u'Email addresses must be unique.')
        return email

    def clean(self):
        """Verify password confirmation match."""
        data = super().clean()
        password = data['password']
        password_confirmation = data['password_confirmation']

        if password != password_confirmation:
            raise forms.ValidationError('Las contraseñas no coinciden.')
        return data

    def save(self):
        """Create base_user and its profile-role"""
        data = self.cleaned_data
        data.pop('password_confirmation')
        user = User.objects.create_user(**data)
        role_chosen = int(data['role'])

        if role_chosen == self.RESIDENT:
            res_prof = ResidentProfile(user=user)
            res_prof.save()
        else:
            wat_prof = WatchmanProfile(user=user)
            wat_prof.save()


class ResidentProfileUpdateForm(forms.ModelForm):
    """ Docstring """
    OWNER = 1
    TENANT = 2
    RELATION_W_PROPERTY = (
        (OWNER, 'PROPIETARIO'),
        (TENANT, 'ARRENDATARIO'),
    )
    property_relation = forms.ChoiceField(
        choices=RELATION_W_PROPERTY,
        label='Relación con el immueble.'
    )
    class Meta:
        model = ResidentProfile
        exclude = ['user']


class WatchmanProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = WatchmanProfile
        exclude = ['user']

src/apps/home/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

# Create your views here.

@login_required
def index(request):
    """ function for homepage """
    # print(request.user.r_profile.property_relation)
    return render(request, 'home/home.html')

src/apps/users/views.py
# Django Imports
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, FormView, UpdateView
from django.contrib.auth import views as auth_views
from django.contrib.auth.mixins import LoginRequiredMixin

# Local Imports
from .forms import SignUpForm, ResidentProfileUpdateForm, WatchmanProfileUpdateForm
from .models import ResidentProfile, WatchmanProfile


class SignUpView(FormView):
    """ Class based view for signup """
    template_name = 'users/signup.html'
    form_class = SignUpForm
    success_url = reverse_lazy('user:login')

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class LoginView(auth_views.LoginView):
    """ Class based view for login """
    template_name = 'users/signin.html'


class LogoutView(LoginRequiredMixin, auth_views.LogoutView):
    """Logout view."""
    template_name = 'users/logged_out.html'


class ResidentProfileUpdateView(LoginRequiredMixin, UpdateView):
    """ Update Resident Profile View """
    template_name = 'users/profile_update.html'
    form_class = ResidentProfileUpdateForm
    model = ResidentProfile
    success_url = reverse_lazy('home:welcome')

    def get_object(self):
        """Return user's profile."""
        return self.request.user.r_profile


class WatchmanProfileUpdateView(LoginRequiredMixin, UpdateView):
    """ Update Resident Profile View """
    template_name = 'users/profile_update.html'
    form_class = WatchmanProfileUpdateForm
    model = WatchmanProfile
    success_url = reverse_lazy('home:welcome')

    def get_object(self):
        """Return user's profile."""
        return self.request.user.w_profile

src/templates/base.html
<!DOCTYPE html>
<html lang="es" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{% block head_content %}VecindApp - Login{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  </head>
  <body>
      <div class="container">
          {% block content %}
          {% endblock %}
      </div>

    {% block footer %}
      <!-- Footer -->
      <footer class="page-footer font-small blue">

        <!-- Copyright -->
        <div class="footer-copyright text-center py-3">© 2018 Copyright:
          <a href="https://www.djangoproject.com/"> Powered by Django 2.0</a>
        </div>
        <!-- Copyright -->

      </footer>
      <!-- Footer -->
    {% endblock%}
  </body>
</html>

src/templates/home/home.html
{% extends 'base.html' %}
{% block head_content %}VecindApp - Home{% endblock %}

{% block content %}
<div class="container">
    <a href="#" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Noticias</a>
    <a href="#" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Quejas y Peticiones</a>
    <a href="#" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Comunidad</a>
    <a href="#" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Reservas</a>
    <a href="#" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Perfil</a>
    <a href="#" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Chat!</a>
</div>
{% endblock %}

src/templates/users/profile_update.html
{% extends 'base.html' %}
{% block head_content %}VecindApp - Profile Update!{% endblock %}

{% block content %}

<div class="container">
    {% if user.role == 1 %}
    <form action="{% url 'user:update_rprofile' %}" method="POST">
    {% elif user.role == 2 %}
    <form action="{% url 'user:update_wprofile' %}" method="POST">
    {% endif %}
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary btn-block mt-5" type="submit">Actualizar</button>
    </form>
</div>
{% endblock %}

src/templates/users/signin.html
{% extends 'base.html' %}

{% block head_content %}VecindApp - Sign In!{% endblock %}

{% block content %}

    {% if form.errors %}
        <p class="alert alert-danger">
            Sú usuario y/o contraseña no coinciden. Por favor intente nuevamente.
        </p>
    {% endif%}

    <form method="POST" action="{% url "user:login" %}">
        {% csrf_token %}

        <div class="form-group">
            <input class="form-control" type="text" placeholder="Nombre de Usuario" name="username" />
        </div>

        <div class="form-group">
            <input class="form-control" type="password" placeholder="Contraseña" name="password" />
        </div>


        <button class="btn btn-primary btn-block mt-5" type="submit">Ingresar!</button>

    </form>

    <p class="mt-4">¿No tienes una cuenta aún? <a href="{% url "user:signup" %}">Regístrate acá.</a></p>

{% endblock %}

src/templates/users/signup.html
{% extends 'base.html' %}

{% block head_content %}VecindApp - Sign Up!{% endblock %}

{% block content %}
    <form action="{% url 'user:signup' %}" method="POST">
       {% csrf_token %}

       {{ form.as_p }}

       <button class="btn btn-primary btn-block mt-5" type="submit">Regístrate!</button>

    </form>
{% endblock %}